function Hd = RR_BPF20
%RR_BPF20 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.5 and Signal Processing Toolbox 8.1.
% Generated on: 07-Apr-2021 18:57:26

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 20;  % Sampling Frequency

N   = 4;    % Order 阶数
Fc1 = 0.1;  % First Cutoff Frequency  截止频率
Fc2 = 0.6;  % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
%  'N,F3dB1,F3dB2'是一个参数模板，它指定了要传递给该函数的参数类型和顺序。
%  'F3dB1'：表示滤波器的第一个3dB截止频率（Lower 3dB Cutoff Frequency）。
%   这是滤波器开始衰减信号的低频边界，通常以赫兹（Hz）为单位。
%   在带通滤波器中，低于这个频率的信号将被衰减。
%  'F3dB2'：表示滤波器的第二个3dB截止频率（Upper 3dB Cutoff Frequency）。
%  这是滤波器开始衰减信号的高频边界。在带通滤波器中，高于这个频率的信号将被衰减。

Hd = design(h, 'butter');

% [EOF]
